import type { Metadata } from "next";
import { Architects_Daughter, Bowlby_One_SC } from "next/font/google";
import "./globals.css";
import InfoBar from "../components/InfoBar";
import Navigation from "../components/Navbar";
import Footer from "../components/Footer";

const archiDaughter = Architects_Daughter({
  variable: "--font-archiDaughter",
  subsets: ["latin"],
  weight: "400"
});

const bowlbyOne = Bowlby_One_SC({
  variable: "--font-bowlbyOne",
  subsets: ["latin"],
  weight: "400"
});

export const metadata: Metadata = {
  title: "Rettungsanker-Feiburg",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${archiDaughter.variable} ${bowlbyOne.variable} bg-stone-900 antialiased`}
      >
        <Navigation />
        <InfoBar />
        {children}
        <Footer />
      </body>
      
    </html>
  );
}
